TRUTH = (
    "Pernahkah Anda ketahuan mengintip sesuatu?",
    "Kapan terakhir kali Anda berbohong kepada orang tua Anda dan mengapa?",
    "Apakah kamu pernah mengupil dan memakannya?",
    "Jika Anda harus memilih antara telanjang atau membuat pikiran Anda muncul dalam gelembung pikiran di atas kepala Anda untuk dibaca semua orang(seperti komik), mana yang akan Anda pilih?",
    "Kapan terakhir kali Anda berbohong?",
    "Kapan terakhir kali kamu menangis dan mengapa?",
    "Apa ketakutan terbesarmu?",
    "Tim bubur diaduk atau dilempar ke kepala bapak kau?",
    "Bunyi seperti apa yang membuatmu terasa ngilu",
    "Apa fantasi terbesarmu?",
    "Apakah Anda memiliki fetish?",
    "Apa sesuatu yang kamu senang ibumu tidak tahu tentang kamu?",
    "Apakah kamu pernah menipu seseorang?",
    "Apa hal terburuk yang pernah Anda lakukan?",
    "Apa hal terakhir yang Anda cari di ponsel Anda?",
    "Setelah Anda menjatuhkan sepotong makanan, berapa lama Anda meninggalkannya di tanah dan kemudian memakannya?",
    "Apa kesenangan bersalah Anda?",
    "Apa kebiasaan terburukmu?",
    "Apakah Anda suka bernyanyi di kamar mandi?",
    "Apakah kamu pernah berbicara dengan dirimu sendiri di cermin?",
    "Apa lagu favoritmu untuk mandi?",
    "Hal apa yang sering membuatmu salting?",
    "Apa yang tidak kamu sukai dari dirimu sendiri?",
    "Apakah Anda lebih suka hidup tanpa internet atau tanpa dirinya?",
    "Jika seseorang menawari Anda iphone ori bukan yang kw untuk putus dengan pacar Anda, apakah Anda akan melakukannya?",
    "Jika Anda terlahir kembali, pada dekade apa Anda ingin dilahirkan?",
    "Jika Anda bisa kembali ke masa lalu untuk menghapus satu hal yang Anda katakan atau lakukan, apakah itu?",
    "Apakah pacarmu pernah mempermalukanmu?",
    "Jika Anda tiba-tiba menjadi tidak terlihat, apa yang akan Anda lakukan?",
    "Pernahkah Anda ketahuan sedang memeriksa seseorang?",
    "Pernahkah Anda melambai pada seseorang yang mengira mereka melihat Anda padahal sebenarnya tidak? Apa yang Anda lakukan ketika Anda menyadarinya?",
    "Berapa lama biasanya Anda tinggal di kamar mandi?",
    "Apakah kamu pernah menangis karena sangat merindukan orang tuamu?",
    "Apakah Anda lebih suka ketahuan mengupil atau buang angin?",
    "Jelaskan mimpi teraneh yang pernah Anda alami. Apakah Anda menyukainya?",
    "Pernahkah Anda memposting sesuatu di media sosial yang Anda sesali? Jika ya lalu tentang apa itu?",
    "Apakah kamu nolep? sudah pasti! coba jelaskanlah mengapa?",
    "Dunia berakhir minggu depan, dan Anda dapat melakukan apapun yang Anda inginkan(bahkan jika itu ilegal). Apa yang akan Anda lakukan?",
    "Apakah Anda termasuk orang yang tidak bisa lepas dari ponsel?",
    "Apa hal paling kekanak-kanakan yang masih kamu lakukan?",
    "Seberapa jauh Anda akan berusaha mendapatkan pria atau wanita impian Anda?",
    "Ceritakan tentang saat Anda mempermalukan diri sendiri di depan orang yang disukai.",
    "Apakah kamu pernah menyimpan buku perpustakaan?",
    "Siapa satu orang yang pura-pura Anda sukai, tetapi sebenarnya tidak?",
    "Film anak-anak apa yang bisa kamu tonton berulang kali?",
    "Apakah Anda memiliki bau kaki yang tidak sedap?",
    "Apakah kamu punya nama panggilan yang konyol?",
    "Kapan terakhir kali kamu mengompol? \o/",
    "Berapa banyak puding yang kamu makan dalam sekali suap?",
    "Pernahkah Anda dengan sengaja menabrak seseorang dengan motor atau sepeda Anda? Jika ya mengapa? (6_9)",
    "Jika Anda harus bercumbu dengan karakter Disney, siapa itu?",
    "Apakah Anda pernah menonton film yang Anda tahu seharusnya tidak Anda tonton?",
    "Pernahkah Anda ingin coba bermain RP(Role-Player)?",
    "Aplikasi apa di ponsel Anda yang paling sering buat Anda buang waktu?",
    "Pernahkah kamu berpura-pura sakit untuk mendapatkan sesuatu? Jika demikian, apa itu?",
    "Makanan apa yang paling banyak kamu makan dalam sekali makan?",
    "Apakah kamu suka melamun ketika kamu sendirian?",
    "Apa yang kamu lakukan saat doi bilang rumah kosong.",
    "Lagu apa di radio atau ponsel cerdas Anda yang Anda nyanyikan setiap kali dinyanyikan?",
    "Apakah Anda memiliki sepasang telinga yang tidak suka mendengarkan gibah?",
    "Apakah Anda takut gelap? dan mengapa..?",
    "Pernahkah Anda melihat setan? jika pernah, bagaimana reaksi setannya saat melihat anda?",
    "Produk seperti iklan di tv apa yang diam-diam ingin Anda beli?",
    "Apakah kamu masih suka mandi bola?",
    "Jika Anda berada di rumah sendiri sepanjang hari, apa yang akan Anda lakukan?",
    "Berapa banyak selfie yang kamu ambil dalam sehari?",
    "Apa yang telah Anda lakukan untuk mencoba menjadi 'lebih keren'?",
    "Kapan terakhir kali Anda menggosok gigi? (-_-)",
    "Apakah kamu pernah makan sesuatu dari lantai?",
    "Apakah kamu suka makan kadal?",
    "Apa yang membuatmu suka merasa bahwa dirimu tidak pantas untuk dia..",
    "Pernahkah kamu ngeghosting seseorang?",
    "Apakah kamu pernah berjalan di atas orang tuamu melakukan 'itu'?",
    "Siapa orang terakhir yang paling kamu sukai? Mengapa?",
    "Apakah kamu pernah diskors dari sekolah?",
    "Jika Anda harus memilih antara telanjang atau pikiran Anda muncul dalam gelembung pikiran di atas kepala Anda untuk dibaca semua orang, mana yang akan Anda pilih?",
    "Apa satu hal yang kamu takut kehilangan?",
    "Apakah kamu menyukai seseorang saat ini?",
    "Satu hal tentang sahabatmu yang membuatmu cemburu?",
    "Apakah kamu akan menipu pacarmu untuk pria kaya?",
    "Apa impian terbesarmu?",
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan mengapa?",
    "Jelaskan pasangan ideal Anda.",
    "Apa hal paling menakutkan yang pernah kamu lakukan?",
    "Apakah kamu pernah mengupil dan memakannya?",
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan mengapa?",
    "Apakah Anda pernah berbohong tentang usia Anda karena menyukai adik kelas?",
    "Apakah kamu pernah ketahuan sedang mengintip seseorang?",
    "Apakah Anda sedang menikmati masa virtual hanya untuk mengisi kekosongan?",
    "Hal kecil apa yang pernah dilakukan seseorang dan bikin kamu senang banget?",
    "Kalau bisa jadi tokoh fiksi selama sehari, mau jadi apa?",
    "Kalau kamu cuma bisa makan satu jenis makanan seumur hidup, mau makan apa?",
    "Siapa orang terakhir yang kamu stalking di media sosial?",
    "Tiga hal apa yang harus gebetan atau pacar kamu punya?",
    "Rate seseorang digrup dari skala 1-10.",
    "musik yang paling tidak kamu sukai?",
    "Siapa celebrity crush kamu?",
    "Skenario paling aneh yang pernah terlintas di pikiranmu tentang kita?",
    "Kalau kamu bisa baca pikiran, pikiran siapa yang bakal kamu baca duluan?",
    "Berapa jam kamu tidur paling lama?",
    "Video TikTok atau YouTube paling memalukan yang pernah kamu tonton?",
    "Film/serial/drama/anime paling memalukan yang pernah kamu tonton?",
    "Apa quotes favoritmu?",
    "Apa insecurity terbesarmu?",
    "Artis atau lagu apa yang paling sering kamu putar pas lagi down?",
    "Hal apa yang kamu harapkan bisa kamu ubah dari diri sendiri?",
    "Apa penyesalan terbesarmu?",
    "Kalau kamu nggak bisa ketemu kita lagi besok, apa yang mau kamu sampaikan atau lakukan?",
    "Hal apa yang kamu harap (nama orang) bisa ubah dari dirinya?",
  
)

DARE = (
    "Tampilkan foto paling memalukan di ponsel Anda"
    "Tampilkan lima orang terakhir yang Anda kirimi SMS dan apa isi pesannya",
    "Biarkan seluruh pemain tod, DM seseorang menggunakan akun Instagram Anda",
    "Makan bawang putih mentah",
    "Lakukan 10 squat",
    "Simpan tiga es batu di mulutmu sampai meleleh",
    "Katakan sesuatu yang kotor kepada orang di sebelah kirimu. Kamu punya teman!",
    "Berikan pijatan kaki pada orang di sebelah kanan Anda",
    "Ucapkan kata pertama yang muncul di pikiranmu",
    "Berikan lap dance kepada seseorang pilihan Anda",
    "Lepaskan empat potong pakaian",
    "Follow dan unfoll sosmed gebetan anda sampai dia menyadarinya(lakukan berulang-ulang)",
    "Jilat sesendok garam",
    "Pejamkan matamu sampai kamu pergi lagi",
    "Kirim virtex ke orang terakhir dikontak Anda",
    "Gigit benda terdekat yang ada disekitarmu",
    "Berpura-puralah menjadi orang di sebelah kananmu selama 10 menit",
    "Makan camilan tanpa menggunakan tangan",
    "Katakan dua hal jujur ​​tentang semua orang dalam grup",
    "Telepon temanmu yang lagi mabar",
    "Cobalah untuk memasukkan seluruh kepalan tanganmu ke dalam mulutmu",
    "Ceritakan kepada semua orang kisah memalukan tentang dirimu",
    "Coba jilat sikumu",
    "Posting selfie tertua di ponsel Anda di story Instagram",
    "Ceritakan kisah paling menyedihkan yang kamu tahu",
    "Melolong seperti serigala selama satu menit(kirim vn)",
    "Biarkan orang lain menggelitikmu dan mencoba untuk tidak tertawa",
    "Masukkan makanan ringan ke dalam mulut Anda sekaligus sebanyak yang Anda bisa",
    "Kirim selfie terbaru Anda.",
    "Kirim selfie terjelekmu.",
    "Kirim tangkapan layar riwayat pencarian Instagram Anda",
    "Kirim tangkapan layar galeri Anda.",
    "Kirim tangkapan layar kotak masuk messenger Anda",
    "Katakan sesuatu yang sangat intim.",
    "Screenshot kotak masuk telegram Anda",
    "Kirim tangkapan layar layar beranda Anda.",
    "Kirim cover lagu favoritmu. ",
    "Gombalin seseorang menggunakan lirik lagu dan kirimkan buktinya.",
    "Akui gebetanmu saat ini ❤️",
    "Nyatakan siapa cinta sejatimu.",
    "Kirim tangkapan layar galeri Anda.",
    "Jadikan foto gebetanmu sebagai profilmu.",
    "Sarankan saya lebih berani.",
    "Tunjukkan daftar chat terakhir di Telegram.",
    "Tunjukkan history dari browser ponsel/laptop kamu.",
    "Tunjukkan history pencarian di Insta/Ttk/Tele/Twt.",
    "Tunjukkan foto-foto/video paling baru di galeri.",
    "Pesan apapun ke seseorang yg kira-kira dia bakal suka banget. Kalau si penerima nggak suka, ulangi ke orang yang berbeda.(ss buktinya)",
    "ngejamet di story whatsapp",
    "pejamkan mata dan scroll kontak wa/tele, siapa yang berhenti terakhir wajib kamu chat",
    "lihatin chat paling memalukan yang masih kamu simpan",
    "random minta maaf ke anonymous sampai dia mau maafin kamu",
    "Call orang yang sudah taken dan bilang kalau kamu suka sama pasangannya.",
    "Tunjukkan like video di TikTok/post yang disukai di Instagram.",
    "Kirim vn dengan lantang pesan yang terakhir kali kamu kirim ke gebetanmu.",
    "Katakan ‘kijang 1 ganti’ di setiap akhir kalimat sampai giliranmu yang selanjutnya.",
    "Lakukan rap gaya bebas selama 2 menit.",
    "Biarkan orang lain membuat status menggunakan akun sosial mediamu.",
    "Peragakan salah satu orang di antara kita sampai ada yang bisa menebak siapa orang yang diperagakan.",

)

QUOTE = (
    "Siapapun bisa jadi apapun.",
    "Jangan biarkan lidahmu memotong lehermu sendiri.",
    "Hidup biarlah berbakti walau tidak dipuji."
    "Tiap bertambah ilmuku, bertambah pula aku mengenal kebodohanku.",
    "Bermimpilah dalam hidup, jangan hidup dalam mimpi.",
    "Gagal dalam perjuangan belum tentu berarti kemunduruan.",
    "Cinta itu Indah, tetapi tidaklah setiap keindahan mengandung cinta",
    "Selalu ikuti kata hatimu. Tapi ingat, bawalah otakmu juga.",
    "Istiqomah memang berat, karena yang ringan itu istirahat.",
    "Sakit hati dan sakit gigi itu sama-sama berawal dari yang manis.",
    "Saat hidup menutup pintu untukmu, buka lagi saja. Itu hanya pintu, itulah cara kerjanya.",
    "Uang adalah sahabat yang terbaik, karenanya banyak sahabat yang berdatangan kepadamu.",
    "Kadang suatu hal buruk itu terjadi untuk memberimu pesan agar berubah dan menjadi lebih baik",
    "Kita terlalu sibuk menginginkan dan mengejar yang besar, tanpa menyadari bahwa kehidupan ini dibangun dari hal-hal kecil yang dilakukan dengan kesungguhan yang besar.",
    "Ada yang lebih bisu dari sepi malam, ketika diammu membuat kepalaku terbentur pertanyaan.",
    "Hidup bukan tentang memaksakan untuk mendapatkan apa yang kamu inginkan, tetapi tentang menghargai apa yang kamu miliki, dan sabar menanti yang akan menghampiri.",
    "Jangan gampang memutuskan perkara ketika kamu sedang marah ataupun senang, pikirkanlah matang-matang dengan suasana hati yang netral.",
    "Jika itu penting bagimu, kamu akan menemukan caranya – Charlie Gilkey",
    "Mata tidak berguna saat pikiran buta.",
    "Anda tidak akan pernah belajar sabar dan berani jika di dunia ini hanya ada kebahagiaan - Helen Keller.",
    "Hati menjadi resah dan gelisah ketika kita terbiasa berandai-andai dalam menyikapi persoalan hidup - Aa Gym.",
    "Balas dendam terbaik adalah menjadikan dirimu lebih baik - Ali bin Abi Thalib.",
    "Kata 'pulang' selalu terdengar jauh lebih indah dari pada 'pergi'. Tetapi orang harus rindu untuk bisa menikmati keindahan pulang - M. Aan Mansur",
    "Jadilah seseorang yang ketika kamu lahir, semua tertawa dan hanya kamu yang menangis. Lalu ketika kamu wafat, semua orang menangis dan kamu tersenyum - Mahatma Gandhi",
    "Bertambahnya usia bukan berarti kita paham segalanya - Dee Lestari.",
    "Mahkota seseorang adalah akalnya. Derajat seseorang adalah agamanya. Sedangkan kehormatan seseorang adalah budi pekertinya.",
    "Bersyukur atas keberhasilan itu sudah biasa, namun bersyukur atas kegagalan itu baru luar biasa",
    "Seberat apapun beban masalah yang kamu hadapi saat ini, percayalah bahwa semua itu tidak pernah melebihi batas kemampuan kamu.",
    "Membantu orang lain tidaklah selalu membutuhkan dana, kamu hanya butuh hati untuk membantu mereka.",
    "Kata-kata motivasi bukan untuk mengubah diri, hanya bagi dia yang terinspirasi agar menyikapi situasi",
    "Jangan hanya melihat siapa yang menyampaikan tapi lihatlah apa yang disampaikannya",
    "Jalan menuju sukses dipenuhi banyak tempat parkir yang menggoda.",
    "Kita memang tidak bisa mengubah arah angin, tapi kita bisa mengendarai laju kemudinya. Sama halnya hidup, kita tidak bisa mengubah skenarionya tapi kita bisa menentukan arahnya",
    "Keyakinan merupakan suatu pengetahuan di dalam hati, jauh tak terjangkau oleh bukti. (Kahlil Gibran, Pujangga)",
    "Sedikit orang kaya yang memiliki harta. Kebanyakan harta yang memiliki mereka. (Robert G. Ingersoll)",
    "Orang termiskin yang aku ketahui adalah orang yang tidak mempunyai apa-apa kecuali uang. (John D. Rockefeller)",
    "Kesempatan Anda untuk sukses di setiap kondisi selalu dapat diukur oleh seberapa besar kepercayaan Anda pada diri sendiri. (Robert Collier)",
    "Kamu tidak mencintai seorang perempuan karena dia cantik, tapi dia cantik karena kamu mencintainya.",
    "Hati mempunyai alasan-alasan yang tidak bisa dimengerti oleh akal.",
    "Orang yang bicara terlalu banyak tentang dirinya sendiri dapat berarti dia sedang menutupi dirinya sendiri. (Friedrich Nietzsche)",
    "Pilihan tergantung dari pemikiran anda untuk mencari 'kebenaran' atau 'pembenaran'.",
    "Sembunyikanlah kebaikan yang kamu lakukan, dan buatlah kebaikan yang telah kamu lakukan itu dikenal (Ali Bin Abi Thalib)",
    "Terkadang saya heran mengapa mereka bangga membicarakan keburukannya sendiri, padahal Tuhan telah menutupinya (bedakan antara munafik dengan mengumbar aib)",
)
